// <auto-generated />
using System;
using Core.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(CustomDbContext))]
    [Migration("20220703121131_alldata")]
    partial class alldata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BaseEntities.Database.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlogCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("BlogCategory");
                });

            modelBuilder.Entity("BaseEntities.Database.BlogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.HasIndex("MasterId");

                    b.ToTable("BlogEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MasterCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterCountryId");

                    b.HasIndex("MasterId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("BaseEntities.Database.ContentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityRelationType")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("ContentDetail");
                });

            modelBuilder.Entity("BaseEntities.Database.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterBlog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("MasterBlog");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterBlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterBlogCategory");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("MasterCity");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterContentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityRelationType")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterContentDetail");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterCountry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterCountry");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MasterProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterProgramId");

                    b.ToTable("MasterProgram");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSchool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("MasterSchool");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSeoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterSeoEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSiteConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstCounterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FirstCounterValue")
                        .HasColumnType("int");

                    b.Property<string>("SecondCounterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecondCounterValue")
                        .HasColumnType("int");

                    b.Property<string>("ThirdCounterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThirdCounterValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterSiteConfig");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5261),
                            FirstCounterValue = 0,
                            SecondCounterValue = 0,
                            ThirdCounterValue = 0,
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5264)
                        });
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSiteSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterSiteSection");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterSss");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Linkedn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterTeam");
                });

            modelBuilder.Entity("BaseEntities.Database.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("ProgramEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.ProgramRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityRelationType")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("ProgramRelation");
                });

            modelBuilder.Entity("BaseEntities.Database.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reference");
                });

            modelBuilder.Entity("BaseEntities.Database.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("School");
                });

            modelBuilder.Entity("BaseEntities.Database.SeoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("SeoEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.SiteConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutUs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("SiteConfig");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b35e3d8-5abb-4da0-9ef6-ccf40dbcf0aa"),
                            AboutUs = "Hakkımızda Yazısı",
                            Address = "Adres Bilgisi",
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5288),
                            Lang = "en-US",
                            MailAddress = "mailadresi@mailadresi.com",
                            MasterId = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb"),
                            PhoneNumber = "05515515454",
                            SiteName = "Klabs Teknoloji",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5289)
                        },
                        new
                        {
                            Id = new Guid("20f6282d-55f6-4fe8-9929-7b03a6a48fdc"),
                            AboutUs = "Hakkımızda Yazısı",
                            Address = "Adres Bilgisi",
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5302),
                            Lang = "tr-TR",
                            MailAddress = "mailadresi@mailadresi.com",
                            MasterId = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb"),
                            PhoneNumber = "05515515454",
                            SiteName = "Klabs Teknoloji",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 191, DateTimeKind.Local).AddTicks(5303)
                        });
                });

            modelBuilder.Entity("BaseEntities.Database.SiteSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("SiteSection");
                });

            modelBuilder.Entity("BaseEntities.Database.SocialNetworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SocialNetworkEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.Sss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Sss");
                });

            modelBuilder.Entity("BaseEntities.Database.TeamEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("BaseEntities.Database.UserComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserComment");
                });

            modelBuilder.Entity("Core.LogModule.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DataRef")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<string>("TableDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Module.Auth.Entities.Newsletter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailAddress")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MailAddress")
                        .IsUnique()
                        .HasFilter("[MailAddress] IS NOT NULL");

                    b.ToTable("Newsletters", (string)null);
                });

            modelBuilder.Entity("Module.Auth.Entities.OperationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7be8d00-4434-4636-a467-c511ea307016"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8779),
                            DisplayName = "Admin",
                            Name = "Admin",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8789)
                        },
                        new
                        {
                            Id = new Guid("d7be8d00-4434-4636-a467-c511ea307018"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8791),
                            DisplayName = "Personel",
                            Name = "Staff",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8792)
                        },
                        new
                        {
                            Id = new Guid("bdc23d6c-2e03-4b0d-b34a-7535d74abbc8"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8794),
                            DisplayName = "Müşteri",
                            Name = "Customer",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8794)
                        });
                });

            modelBuilder.Entity("Module.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb"),
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8860),
                            FirstName = "admin",
                            LastName = "admin",
                            LoginName = "admin",
                            MailAddress = "admin@admin.com",
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(8861)
                        });
                });

            modelBuilder.Entity("Module.Auth.Entities.UserOperationClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperationClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOperationClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9744),
                            OperationClaimId = new Guid("d7be8d00-4434-4636-a467-c511ea307016"),
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9745),
                            UserId = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb")
                        },
                        new
                        {
                            Id = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06947eb"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9747),
                            OperationClaimId = new Guid("d7be8d00-4434-4636-a467-c511ea307018"),
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9748),
                            UserId = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb")
                        });
                });

            modelBuilder.Entity("Module.Auth.Entities.UserPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HashedPassword")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPasswords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cbe7509a-3e0d-441e-9e61-905742c652d5"),
                            CreateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9724),
                            HashedPassword = new byte[] { 33, 156, 91, 219, 2, 252, 18, 248, 1, 212, 106, 193, 46, 29, 22, 164, 26, 65, 189, 190, 20, 122, 133, 47, 73, 10, 108, 20, 156, 119, 108, 145, 40, 62, 15, 90, 122, 107, 70, 249, 171, 232, 247, 207, 224, 31, 232, 72, 135, 153, 226, 202, 90, 8, 243, 124, 20, 61, 127, 60, 73, 13, 118, 6 },
                            PasswordSalt = new byte[] { 164, 253, 95, 37, 182, 131, 104, 185, 192, 189, 131, 109, 115, 48, 39, 250, 53, 160, 211, 29, 131, 8, 75, 248, 175, 102, 202, 71, 154, 147, 223, 185, 155, 234, 60, 202, 184, 235, 11, 66, 245, 2, 207, 90, 210, 190, 233, 50, 9, 69, 49, 98, 51, 174, 138, 57, 20, 190, 175, 99, 169, 128, 26, 161, 254, 123, 98, 55, 239, 138, 90, 248, 240, 39, 251, 22, 218, 175, 130, 142, 55, 2, 168, 5, 20, 17, 181, 193, 120, 113, 141, 177, 128, 170, 89, 6, 107, 4, 6, 23, 86, 152, 211, 116, 132, 25, 222, 151, 5, 26, 184, 222, 51, 29, 98, 24, 59, 231, 163, 168, 255, 94, 8, 92, 128, 236, 102, 131 },
                            UpdateTime = new DateTime(2022, 7, 3, 15, 11, 31, 190, DateTimeKind.Local).AddTicks(9725),
                            UserId = new Guid("c5073b7b-4c66-4b12-ae40-e3f9e06949eb")
                        });
                });

            modelBuilder.Entity("Module.Auth.Entities.UserValidationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValidationCodeType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserValidationCodes", (string)null);
                });

            modelBuilder.Entity("BaseEntities.Database.BlogCategory", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterBlogCategory", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.BlogEntity", b =>
                {
                    b.HasOne("BaseEntities.Database.BlogCategory", null)
                        .WithMany("Blogs")
                        .HasForeignKey("BlogCategoryId");

                    b.HasOne("BaseEntities.Database.MasterBlog", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.City", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterCountry", null)
                        .WithMany("Cities")
                        .HasForeignKey("MasterCountryId");

                    b.HasOne("BaseEntities.Database.MasterCity", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.ContentDetail", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterContentDetail", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.CountryEntity", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterCountry", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterBlog", b =>
                {
                    b.HasOne("BaseEntities.Database.BlogCategory", "BlogCategory")
                        .WithMany()
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategory");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterCity", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterCountry", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterProgram", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterProgram", "MasterProgramEntity")
                        .WithMany()
                        .HasForeignKey("MasterProgramId");

                    b.Navigation("MasterProgramEntity");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSchool", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterCity", "City")
                        .WithMany("Schools")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("BaseEntities.Database.ProgramEntity", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterProgram", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.ProgramRelation", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterProgram", "MasterProgram")
                        .WithMany("ProgramRelations")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterProgram");
                });

            modelBuilder.Entity("BaseEntities.Database.School", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterSchool", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.SeoEntity", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterSeoEntity", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.SiteConfig", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterSiteConfig", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.SiteSection", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterSiteSection", "Master")
                        .WithMany()
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.Sss", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterSss", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("BaseEntities.Database.TeamEntity", b =>
                {
                    b.HasOne("BaseEntities.Database.MasterTeam", "Master")
                        .WithMany("Childrens")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");
                });

            modelBuilder.Entity("Module.Auth.Entities.UserOperationClaim", b =>
                {
                    b.HasOne("Module.Auth.Entities.OperationClaim", "OperationClaim")
                        .WithMany("OperationClaimUsers")
                        .HasForeignKey("OperationClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module.Auth.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperationClaim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Module.Auth.Entities.UserPassword", b =>
                {
                    b.HasOne("Module.Auth.Entities.User", "User")
                        .WithMany("UserPasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Module.Auth.Entities.UserValidationCode", b =>
                {
                    b.HasOne("Module.Auth.Entities.User", "User")
                        .WithMany("UserValidationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseEntities.Database.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterBlog", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterBlogCategory", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterCity", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("Schools");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterContentDetail", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterCountry", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("Cities");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterProgram", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("ProgramRelations");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSchool", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSeoEntity", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSiteConfig", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterSss", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("BaseEntities.Database.MasterTeam", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Module.Auth.Entities.OperationClaim", b =>
                {
                    b.Navigation("OperationClaimUsers");
                });

            modelBuilder.Entity("Module.Auth.Entities.User", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserPasswords");

                    b.Navigation("UserValidationCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
